// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsIRQafTmfwN_rldunt64N-XBgh06-fuc',
    appId: '1:398787206135:web:dddc4c8e701f433dc7acf2',
    messagingSenderId: '398787206135',
    projectId: 'fashionstore-b4c78',
    authDomain: 'fashionstore-b4c78.firebaseapp.com',
    storageBucket: 'fashionstore-b4c78.firebasestorage.app',
    measurementId: 'G-TC3DHB541Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-bXg1K0ZnvCaKsGYtTOaz476aDsznms',
    appId: '1:398787206135:android:eab1270248de5b25c7acf2',
    messagingSenderId: '398787206135',
    projectId: 'fashionstore-b4c78',
    storageBucket: 'fashionstore-b4c78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALfiYM3iUXkgCxMMmoZfrOxPEDH25TD1Y',
    appId: '1:398787206135:ios:b4cf18e6fb9b01ecc7acf2',
    messagingSenderId: '398787206135',
    projectId: 'fashionstore-b4c78',
    storageBucket: 'fashionstore-b4c78.firebasestorage.app',
    iosBundleId: 'com.example.th3Fashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALfiYM3iUXkgCxMMmoZfrOxPEDH25TD1Y',
    appId: '1:398787206135:ios:b4cf18e6fb9b01ecc7acf2',
    messagingSenderId: '398787206135',
    projectId: 'fashionstore-b4c78',
    storageBucket: 'fashionstore-b4c78.firebasestorage.app',
    iosBundleId: 'com.example.th3Fashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsIRQafTmfwN_rldunt64N-XBgh06-fuc',
    appId: '1:398787206135:web:fee52e271f0cdb6bc7acf2',
    messagingSenderId: '398787206135',
    projectId: 'fashionstore-b4c78',
    authDomain: 'fashionstore-b4c78.firebaseapp.com',
    storageBucket: 'fashionstore-b4c78.firebasestorage.app',
    measurementId: 'G-PYFLG1P9EJ',
  );
}
